### ISSUE TITLE
myman doesn't exist

### ISSUE THREAD

**Issue by ammgws** [WnndGws/scripts#27]
Remove from readme?

>     myman
>         Check tldr for a program, and if not there then show manual or --help for it
>

**Comment by WnndGws** [comment]
Need to update README in general. scrips have changed SIGNIFICANTLY. Ideally would write a script to extract the description from each file and add it to the README

**Comment by ammgws** [comment]
Ohk

**Comment by ammgws** [comment]
Looks good now
